language: node_js
sudo: false
node_js:
  - "6.9"
install:
  - curl -L -o yarn.tar.gz "https://yarnpkg.com/latest.tar.gz" >/dev/null
  - mkdir yarn
  - tar zxf yarn.tar.gz -C yarn --strip 1
  - ./yarn/bin/yarn install
script:
  - gulp=node_modules/gulp/bin/gulp.js && gulp clean && gulp build
  - (cd build && tar -zcf ../build.tar.gz ./*)
  - (cd build && zip -r ../build.zip ./*)
deploy:
  provider: releases
  api_key:
    secure: gJ1p32NIh9wFggGHfaoU2dVAEo3pO8mxYvXAE6vfElIdmEEi9MLCgdm/XRVlDrPj7nPyXSQRYK2jWOtD7F/r5Or2yRVqR55RXfu9jrQIxV/k+RyDW7rwewFohdHrlfQC+Og3CIhqHDec03Q3VGZQAvTOzM2aZsBTOu3bmlxO89ii5jKwoZ92ueMLXgKFVDi52jfFZND7e0wXvTtHtHaawj6OcxIIOYBXQ8tE6psScBcqLGXC+PvKtaRoHcqjbjZNoITlqgtREEjz+xyVGVjn1is3ib0mpvCRJ7aylthit4PPfVOAzmJsR7zoJMu22pXcWKo/mKOyr/0/FKVWBTuWB1IhKYkNaznqEquCTc5wgi5ozE3LkWTxUJ4MFvbemQLVKw39VEHxmYFVl5UYz52jn8NBFCIoMzCCBd520nM/GZhLbHoUnwEtaJjg7t6wrVcXZ3Uo87ROuDrPVrDoSRNwSn2oekJpxwALuyOYo1kTl/wM97QTG+VL5H+r5PL4eUVcswtt4B/fbAS7BMvVCoTRBsmoURhGeJVnTJkprYxaJzH6Iq9Pb1E84msUW68qTR2BhGKouqxU65k2J8sYhgD/VL6HYtuLVh/lViykwYIfPU7Z5y8EG8YbwFowXAsmbTwGtekMFJL3incgl2JnVNOO+oynSDvZpDkMFBbDuRGSq2g=
  file:
    - build.zip
    - build.tar.gz
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: WvTaprkryt7qwCr4LiYVdU9OX6R8Oxba2dJ+aJdNgtKux3pj1RMyE72EA5S5IP/Qq5rP/e6AMvzfeCDLy+Hqf7eDMgRb+Vsi4LJAneGnoMytv4sGue39WfEJk6mdPNzp1li23hsUqyKQNdMouxv1spG9Xbe4P+fPRECeXIuoa/RcJq+SFYfv6ioxJUahTk3r0+4yWGkB2Ivv1yZysx1Bb9tLw+aly2pscHWhQcWcXU6t+2kpVyymWvJvPKucyxg0h40ZBpYMd/BYUxP8r2sRA1o1l0WfQOUhiUL8BF/xqf4K4CZsSLr61LZqH0tsignNwBPXnOGPUWdeRs+xp9a+0ngvG8RUOpsKLxlQjBJ6nsh1n6ArSMHT53mdWArvp0gode+yLJodj6pi7nstPz4l32m9NZCeqM/nLBOaq8X7mPW13Wn1UeVi2VFlnvRX/Tx5qmpwwJyh969rUkiod9deJt89heOp/LzYK+58ctaIgdc577KGRcpnq8lh7iN8Z0HLmIUWPACYkfimmLI3pMNmhihS/tByfa7SC67lofrNHQVikFfYn/xAydCB8YbF1dTw25EUEvCgJS37Mw9GjRohXYOV/hwT0DQzgfsAL6o+bHak57UbrI9JVGMYZNclKJlOT8ORhDjCJmJ9lVNVuj2XhhqGrgXhKKnCGbxuwiKOJBo=
